apiVersion: v1
kind: Secret
metadata: 
  name: asto-lms-secrets
  namespace: asto-lms
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDIS_PASSWORD: redis
  JWT_SECRET: $2a$10$9zbxpYQNin6BLCUVnx93QeMHqph.o5KNOlNt0qPhY4dUpBnzAEPJq
  SMTP_USERNAME: testing.test0397@gmail.com
  SMTP_PASSWORD: sztuoezstqdowpom
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  ZOOM_ACCOUNT_ID: oOjiX8G5Tvq3o1e2DgwxDQ
  ZOOM_CLIENT_ID: TENC7I4Rj5szSikQ6vw
  ZOOM_CLIENT_SECRET: rhDUAA3ADIVppdBmp7z23y79YN6YD3uE
  ZOOM_SECRET_TOKEN: Nh1PR9TeRfCbb-pqns6y4Q
  ZOOM_USER_ID: testing.test0397@gmail.com
  config.env: |-
    export MINIO_ROOT_USER="minioadmin"
    export MINIO_ROOT_PASSWORD="minioadmin"
    export MINIO_BROWSER="on"