apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-file-instructor-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: file-instructor
spec:
  parentRefs:
  - name: asto-lms-gateway
    sectionName: http
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: Exact
        value: /api/v1/files
      method: POST
    - path:
        type: PathPrefix
        value: /api/v1/files/
      method: DELETE
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.nginx.org
        kind: SnippetsFilter
        name: lms-instructor-policy
    backendRefs:
    - name: file-service
      port: 8004

