apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-course-public-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: course-public
spec:
  parentRefs:
  - name: asto-lms-gateway
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: Exact
        value: /api/v1/categories
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/categories/
      method: GET
    - path:
        type: Exact
        value: /api/v1/courses
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/courses/
      method: GET
    - path:
        type: Exact
        value: /api/v1/course-offerings
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/course-offerings/
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/course-sections/
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/section-modules/
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/courses/swagger
    - path:
        type: Exact
        value: /health
      method: GET
    backendRefs:
    - name: course-service
      port: 8005
