apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-auth-public-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: auth-public
spec:
  parentRefs:
  - name: asto-lms-gateway
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: Exact
        value: /api/v1/auth/register
    - path:
        type: Exact
        value: /health
    - path:
        type: Exact
        value: /api/v1/auth/login
    - path:
        type: Exact
        value: /api/v1/auth/forgot-password
    - path:
        type: Exact
        value: /api/v1/auth/verify-otp
    - path:
        type: Exact
        value: /api/v1/auth/reset-password
    - path:
        type: Exact
        value: /api/v1/auth/verify-email
    - path:
        type: Exact
        value: /api/v1/auth/request-email-verify
    - path:
        type: Exact
        value: /api/v1/auth/refresh-token
    - path:
        type: Exact
        value: /api/v1/auth/verify
    - path:
        type: PathPrefix
        value: /api/v1/auth/swagger
    backendRefs:
    - name: auth-service
      port: 8002

