apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-user-admin-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: user-admin
spec:
  parentRefs:
  - name: asto-lms-gateway
    sectionName: http
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: Exact
        value: /api/v1/users
      method: GET
    - path:
        type: Exact
        value: /api/v1/users
      method: POST
    - path:
        type: PathPrefix
        value: /api/v1/users/
      method: GET
    - path:
        type: PathPrefix
        value: /api/v1/users/
      method: PUT
    - path:
        type: PathPrefix
        value: /api/v1/users/
      method: DELETE
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.nginx.org
        kind: SnippetsFilter
        name: lms-instructor-policy
    backendRefs:
    - name: user-service
      port: 8001