apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: asto-lms-gateway
  namespace: asto-lms
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: asto-lms.local
    allowedRoutes:
      namespaces:
        from: Same

