apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-enrollment-public-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: enrollment-public
spec:
  parentRefs:
  - name: asto-lms-gateway
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/enrollments/swagger  
    backendRefs:
    - name: enrollment-service
      port: 8007

