apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-zoom-admin-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: zoom-admin
spec:
  parentRefs:
  - name: asto-lms-gateway
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/zoom/meetings
      method: DELETE
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.nginx.org
        kind: SnippetsFilter
        name: lms-admin-policy
    backendRefs:
    - name: zoom-service
      port: 8006

