apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lms-file-public-route
  namespace: asto-lms
  labels:
    app.kubernetes.io/component: file-public
spec:
  parentRefs:
  - name: asto-lms-gateway
    sectionName: http
  hostnames:
  - asto-lms.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/buckets/course-thumbnails/
    - path:
        type: PathPrefix
        value: /api/v1/files/swagger
    backendRefs:
    - name: file-service
      port: 8004

